version: "3"
services:
  db:
    image: linuxserver/mariadb
    networks:
      network:
        ipv4_address: 10.0.0.2
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
    volumes:
      - "./db:/config"
    ports:
      - 3306:3306
    restart: unless-stopped
  db_pma:
    image: phpmyadmin
    networks:
      network:
        ipv4_address: 10.0.0.3
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      PMA_USER: root
      PMA_PASSWORD: pmapassword
    ports:
      - 8088:80
    restart: unless-stopped
  www:
    image: php:7.4-apache
    networks:
      network:
        ipv4_address: 10.0.0.4
    depends_on:
      - db
    volumes:
      - "./html:/var/www/html"
      - "apache:/etc/apache2"
      - "php:/usr/local/etc/php"
      - "./cert:/etc/cert"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
volumes:
  apache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR}/apache
  php:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR}/php
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
